[package]
name = "ratatui-kit"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
generational-box = "0.6.2"
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "=0.30.0-alpha.4"
tokio = { version = "1.45.1", features = ["full"] }
any_key = "0.1.1"
